[env]
[env.calibration]
token_contract_address = "0x91B25A65b295F0405552A4bbB77879ab5e38166c"
payment_contract_address = "0xF0F98f476b1a5c1c6EA97eEb23d8796F553246d9"

[env.prod]
token_contract_address = ""
payment_contract_address = ""

[chain]
[chain.swan-saturn]
id = 2024
rpc = "https://saturn-rpc.swanchain.io"

[chain.swan-testnet]
id = 8598668088
rpc = "https://rpc-testnet.swanchain.io"

[chain.polygon-mumbai]
id = 80001
rpc = "https://rpc-mumbai.maticvigil.com"

[chain.sepolia]
id = 11155111
rpc = "https://sepolia.etherscan.io"