from enum import Enum


class SDK(Enum):
    Docker: str = "Docker"
    Streamlit: str = "Streamlit"
    Static: str = "Static"


class License(Enum):
    openrail = "openrail"
    bigscience_openrail_m = "bigscience-openrail-m"
    creativeml_openrail_m = "creativeml-openrail-m"
    bigscience_bloom_rail_1_0 = "bigscience-bloom-rail-1.0"
    afl_3_0 = "afl-3.0"
    apache_2_0 = "apache-2.0"
    artistic_2_0 = "artistic-2.0"
    bsl_1_0 = "bsl-1.0"
    bsd = "bsd"
    bsd_2_clause = "bsd-2-clause"
    bsd_3_clause = "bsd-3-clause"
    bsd_3_clause_c = "bsd-3-clause-clear"
    c_uda = "c-uda"
    cc = "cc"
    cc0_1_0 = "cc0-1.0"
    cc_by_2_0 = "cc-by-2.0"
    cc_by_2_5 = "cc-by-2.5"
    cc_by_3_0 = "cc-by-3.0"
    cc_by_4_0 = "cc-by-4.0"
    cc_by_sa_3_0 = "cc-by-sa-3.0"
    cc_by_sa_4_0 = "cc-by-sa-4.0"
    cc_by_nc_2_0 = "cc-by-nc-2.0"
    cc_by_nc_3_0 = "cc-by-nc-3.0"
    cc_by_nc_4_0 = "cc-by-nc-4.0"
    cc_by_nd_4_0 = "cc-by-nd-4.0"
    cc_by_nc_nd_3_0 = "cc-by-nc-nd-3.0"
    cc_by_nc_nd_4_0 = "cc-by-nc-nd-4.0"
    cc_by_nc_sa_2_0 = "cc-by-nc-sa-2.0"
    cc_by_nc_sa_3_0 = "cc-by-nc-sa-3.0"
    cc_by_nc_sa_4_0 = "cc-by-nc-sa-4.0"
    wtfpl = "wtfpl"
    ecl_2_0 = "ecl-2.0"
    epl_1_0 = "epl-1.0"
    epl_2_0 = "epl-2.0"
    eupl_1_1 = "eupl-1.1"
    agpl_3_0 = "agpl-3.0"
    gfdl = "gfdl"
    gpl = "gpl"
    gpl_2_0 = "gpl-2.0"
    gpl_3_0 = "gpl-3.0"
    lgpl = "lgpl"
    lgpl_2_1 = "lgpl-2.1"
    lgpl_3_0 = "lgpl-3.0"
    isc = "isc"
    lppl_1_3c = "lppl-1.3c"
    ms_pl = "ms-pl"
    mit = "mit"
    mpl_2_0 = "mpl-2.0"
    odc_by = "odc-by"
    odbl = "odbl"
    openrailpp = "openrail++"
    osl_3_0 = "osl-3.0"
    postgresql = "postgresql"
    ofl_1_1 = "ofl-1.1"
    ncsa = "ncsa"
    unlicense = "unlicense"
    zlib = "zlib"
    pddl = "pddl"
    lgpl_lr = "lgpl-lr"
    unknown = "unknown"
